apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: 'external-secrets'
    targetRevision: '0.9.11'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
